const DATA = {
	"placeholder": {
		"name": "placeholder",
		"file": "placeholder",
		"type": "placeholder",
		"target": "enemy",
		"cost": 7,
		"dexterity": 7,
		"description": "Yo... \n Existo.\n No me pidas más",
		"actions": []
	},
	"sword": {
		"name": "Sword",
		"file": "sword",
		"type": "attack",
		"target": "enemy",
		"cost": 1,
		"dexterity": 3,
		"description": "Úsame... \n ¡y mata!",
		"exiled": false,
		"actions": [
			["base_damage", {"amount": -1}],
		],
	},
	"attack_1": {
		"name": "Sword",
		"file": "attack_1",
		"type": "attack",
		"target": "enemy",
		"cost": 1,
		"dexterity": 3,
		"description": "Úsame... \n ¡y mata!",
		"exiled": false,
		"actions": [
			["base_damage", {"amount": -1}],
		],
	},
	"attack_2": {
		"name": "Sword+",
		"file": "attack_2",
		"type": "attack",
		"target": "enemy",
		"cost": 1,
		"dexterity": 3,
		"description": "Yo no corto, yo rajo.",
		"exiled": false,
		"actions": [
			["base_damage", {"amount": -3}],
		],
	},
	"attack_3": {
		"name": "Sword++",
		"file": "attack_3",
		"type": "attack",
		"target": "enemy",
		"cost": 1,
		"dexterity": 3,
		"description": "Prearate a morir",
		"exiled": false,
		"actions": [
			["base_damage", {"amount": -5}],
		],
	},
	"water": {
		"name": "Sword",
		"file": "sword",
		"type": "attack",
		"target": "enemy",
		"cost": 1,
		"dexterity": 3,
		"description": "A veh si te lavas",
		"exiled": false,
		"actions": [
			["apply_condition", {"amount": +6, "condition": "water_damage"}],
		],
	},
	"potion": {
		"name": "Potion",
		"file": "potion",
		"type": "magic",
		"target": "player",
		"cost": 2,
		"dexterity": 2,
		"description": "Yo curo :)",
		"exiled": false,
		"actions": [
			["apply_condition", {"amount": +4, "condition": "curandome"}],
		],
	},
	"fire": {
		"name": "Fire",
		"file": "fire",
		"type": "magic",
		"target": "enemy",
		"cost": 7,
		"dexterity": 7,
		"description": "Bwahaha ha ha",
		"exiled": true,
		"actions": [
			["base_damage", {"amount": -1}],
			["apply_burn", {"amount": 2}],
		],
	},
	"thump": {
		"name": "Thump",
		"file": "thump",
		"type": "attack",
		"target": "enemy",
		"cost": 1,
		"dexterity": 1,
		"description": "Toma guantazo",
		"exiled": false,
		"actions": [
			["base_damage", {"amount": -1}],
		],
	},
	"super_thump": {
		"name": "Super Thump",
		"file": "super_thump",
		"type": "attack",
		"target": "enemy",
		"cost": 2,
		"dexterity": 1,
		"description": "Toma guantazo lleno de odio",
		"exiled": true,
		"actions": [
			["base_damage", {"amount": -3}],
		],
	}
}
